repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=no]
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.25.1
  hooks:
  - id: pyproject-fmt
    language_version: python3.13
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v22.1.5
  hooks:
  - id: clang-format
- repo: https://github.com/MarcoGorelli/cython-lint
  rev: v0.21.0
  hooks:
  - id: cython-lint
    language_version: python3.13
  - id: double-quote-cython-strings
    language_version: python3.13
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.20
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: v1.26.1
  hooks:
  - id: zizmor
    language_version: python3.13
    args: [--fix=safe, --offline]
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.12
  hooks:
  - id: actionlint
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
